/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalproject;

import java.util.*;
import java.lang.*;

/**
 *
 * @author jacobbushdiecker
 */
public class PlayerManager {
    public static void main(String[] args){
        /*Scanner input = new Scanner(System.in);
        
        System.out.print("Enter a character to add to your roster: ");
        String choice = input.nextLine();
        
        
        CreatePlayers(choice);
        */
    }
    
    public static void CreatePlayers(String choice){
        CharSequence cs1 = choice;
        ArrayList<String> myRoster = new ArrayList<>();
        for(int j = 0; j < allPlayers.length; j++){
            allPlayers[j] = allPlayers[j].toLowerCase();
            if(allPlayers[j].contains(cs1)){
                myRoster.add(allPlayers[j]);
                    break;
                }
            }
        for(int k = 0; k < myRoster.size(); k ++){
            System.out.println(myRoster.get(k) + " has been added to "
                    + "your roster.");
        }
    }
    
    public static String allPlayers[] = {"Correa, Kamalel", "Cox, Morgan", "Davis, Carl",
        "Dixon, Kenneth", "Flacco, Joe", "Gillmore, Crockett", "Jefferson, Tony", 
        "Jernigan, Timmy", "Judon, Matthew", "Koch, Sam", "Levine, Anthony", "Lewis, Alex", 
        "Mallet, Ryan", "McClellan, Albert", "Moore, Chris", "Mosley, C.J.", "Perriman, Breshad", 
        "Pierce, Michael", "Pitta, Dennis", "Pughsley, Jarrod", "Smith, Jimmy", "Smith, Za'Darius",
        "Stanley, Ronnie", "Suggs, Terrell", "Taliaferro, Lorenzo", "Tucker, Justin", "Urban, Brent", 
        "Urschel, John", "Wallace, Mike", "Waller, Darren", "Weddle, Eric", "Terrence, West",
        "Williams, Brandon", "Woodhead, Danny", "Yanda, Marshall", "Young, Taxon", 
        "Allen, Javorius", "Canady, Maurice", "Carr, Brandon", "Albright, Bryson", "Atkins, Geno", "Benwikere, Bene", 
        "Bernard, Giovani", "Billings, Andrew", "Bodine, Russell", "Boling, Clint", "Boyd, Tyler",
        "Brown, Chris", "Brown, Jonathan", "Brown, Ryan", "Bullock, Randy", "Burfict, Vontaze",
        "Carson, Tra", "Clarke, Will", "Core, Cody", "Dalton, Andy", "Dawson, P.J.", "Dean, David",
        "Dennard, Darqueze", "Driskel, Jeff", "Dunlap, Carlos", "Eifert, Tyler", "Erickson, Alex",
        "Fejedelem, Clayton", "Fisher, Jake", "Flowers, Marquis", "Green, A.J.", "Hardison, Marcus",
        "Harris, Clark", "Hewitt, Ryan", "Hill, Jeremy", "Hopkins, Trey", "Huber, Kevin", 
        "Lloka, George", "Jackson, William", "Johnson, Michael", "Johnson, T.J.", "Jones, Adam",
        "Kirkpatrick, Dre", "Kroft, Tyler", "Kumerow, Jake", "LaFell, Brandon", "McCarron, AJ",
        "McRae, Tony", "Minter, Kevin", "Ogbuehi, Cedric", "Peerman, Credric", "Redomd, Alex",
        "Rey, Vincent", "Russell, Alonzo", "Russell, KeiVarae", "Shaw, Josh", "Sims, Pay",
        "Smith, Andrew", "Smith, Derron", "Thompson, Brandon", "Uzomah, C.J.", "Vigil, Nick",
        "Westerman, Christian", "Williams, DeShawn", "Williams, Shawn", "Winston, Eric", "Alexander, Dominuque", "Alford, Mario", "Atkinson III, George",
        "Bailey, Alvin", "Barnidge, Gary", "Bitonio, Joel", "Boddy-Calhoun, Briean",
        "Boyce, Josh", "Britt, Kenny", "Bryant, Desmond", "Burgess, James", "Burley, Marcus",
        "Caldwell, Trey", "Campbell, Ibraheim", "Carder, Tank", "Coleman, Corey", "Coleman, Shon",
        "Coley, Trevon", "Collins, Jamie", "Colquitt, Britton", "Cooper, Xavier", "Crowell, Isaiah",
        "Currie, Justin", "Davis, Demario", "DeValve, Seth", "Drango, Spencer", "Elston, Trae",
        "Erving, Cameron", "Fabiano, Anthony", "Greco, John", "Haden, Joe", "Hall, Rannell",
        "Higgins, Rashard", "Hillarry, Darius", "Hogan, Kevin", "Holmes, Tyrone", "Holtz, J.P.",
        "Howard, Tracy", "Hughlett, Charley", "Ikard, Gabe", "Jackson, Darius", "Johnson, Duke",
        "Johnson, Cam", "Kessley, Cody", "Kindred, Derrick", "Kirksey, Christian",
        "Lawrence-Stample, Nile", "Leslie, Jordan", "Louis, Ricardo", "Maher, Brett", "Martin, Marcus",
        "McCants, Matt", "Meder, Jamie", "Nassib, Carl", "Ogbah, Emmanuel", "Orchard, Nate",
        "Osweiler, Brock", "Parkey, Cody", "Payton, Jordan", "Powell, Tyvis", "Reiter, Austin",
        "Reynolds II, Ed", "Schobert, Joe", "Shelton, Danny", "Sterup, Zach", "Taylor, Jamar",
        "Telfer, Randall", "Thomas, Joe", "Tretter, JC", "Vitale, Danny", "Wright, Gabe",
        "Wright, James", "Zeitler, Kevin", "Alualu, Tyson", "Ayers, Demarcus", "Bell, Le'Von", "Berry, Jordan",
        "Blount, Akil", "Boswell, Chris", "Brown-Dukes, Brandon", "Brown, Antonio", 
        "Canadar, Kameron", "Chickillo, Anthony", "Coates, Sammie", "Cockrell, Ross",
        "Dangerfield, Jordan", "Davis, Knile", "Davis, Sean", "DeCastro David", "Dixon, Brandon",
        "Ducre, Gred", "Dupree, Bud", "Fanaika, Jason", "Feiler, Matt", "Finney, B.J.", "Fort, L.J.",
        "Foster, Ramon", "Friend, Kyle", "Gay, William", "Gilbert, Marcus", "Golden, Robert", 
        "Golson, Senquez", "Green, Ladarius", "Grimble, Xavier", "Hagen, Jacob", "Hamilton, Cobi",
        "Hargrave, Javon", "Harrison, James", "Hawkins, Jerald", "Heyward-Bey, Darrius", 
        "Heyward, Cameron", "Hilton, Mike", "Hooks, Lavon", "Hubbard, Chris", "Hughes, AJ", 
        "Huguenin, Farrington", "Hunter, Justin", "James, Jesse", "Johnson, David", "Johnson, Devonte",
        "Johnson, Gus", "Johnson, Steven", "Jones, Landry", "Malleck, Ryan", "Matakevich, Tyler", 
        "Matthews, Mike", "Maxey, Johnny", "McCullers, Daniel", "Mettenberger, Zach", 
        "Mihalik, Brian", "Milton, Keavon", "Mitchell, Mike", "Moats, Arthur", "Nix, Roosevelt",
        "Philon, Roy", "Pouncey, Maurkice", "Roethlisberger, Ben", "Rogers, Eli",
        "Sensabaugh, Coty", "Severin, Canaan", "Shabazz, Al-Hajj", "Shazier, Ryan", 
        "Smith, Dreamius", "Stewart, Dez", "Toussaint, Fitzgerald", "Tucker, Marcus", "Tuitt, Stephon", 
        "Villanueva, Alejandro", "Walton, L.T.", "Warren, Greg", "Williams, Trey", "Williams, Vince", "Alexander, Lorenzo", "Anderson, Colt", "Annen, Blake", "Banyard, Joe",
        "Brown, Philly", "Brown, Preston", "Butler, Jeremy", "Clay, Charles", "Coleman, Deandre",
        "Darby, Ronald", "Dareus, Marcell", "Davis, Ryan", "DiMarco, Patrick", "Dowling, Jonathan", 
        "Ducasse, Vladimir", "Ferguson, Reid", "Gaines, Charles", "Gary, Shamiel", "Gillislee, Mike",
        "Glenn, Cordy", "Groy, Ryan", "Hauschka, Stephen", "Henderson, Seantrel", "Holmes, Andre",
        "Hughes, Jerry", "Humber, Ramon", "Hyde, Micah", "Incognito, Richie", "Johnson, Leonard",
        "Jones, Cardale", "Kouandjio, Cyrus", "Lawson, Shaq", "Lewis, Dezmin", "Lewis, Patrick",
        "Listenbee, Kolby", "McCoy, LaSean", "Miller, John", "Mills, Jordan", "O'Leary, Nick", 
        "O'Neal, Cedric", "Ola, Michael", "Powell, Joe", "Powell, Walter", "Poyer, Jordan",
        "Ragland, Reggie", "Roberson, Marcus", "Schmidt, Colton", "Seymour, Kevon", "Tate, Brandon",
        "Taylor, Tyrod", "Thomas, Logan", "Tolbert, Mike", "Valles, Max", "Washington, Adolphus",
        "Washington, Corey", "Watkins, Sammy", "Williams, Jonathan", "Williams, Kyle", "Wood, Eric",
        "Woodrum, Josh", "Worthy, Jerel", "Aikens, Walt", "Ajayi, Jay", "Allen, Nate", "Alonso, Kiko", "Barrow, Lamin",
        "Branch, Andre", "Brendel, Jake", "Bushrod, Jermon", "Carroo, Leonte", "Chapman, Winston",
        "Darr, Matt", "Davis, Jesse", "Denney, John", "Doughty, Brandon", "Drake, Kenyan", 
        "Duarte, Thomas", "Fasano, Anthony", "Fede, Terrence", "Franks, Andrew", "Grant, Jakeem",
        "Gray, MarQueis", "Hayes, William", "Hendy, A.J.", "Hewitt, Neville", "Howard, Xavien",
        "Hull, Mike", "James, Ja'Wuan", "Johnson, Storm", "Jones, Reshad", "Jordan, Dion", 
        "Lacey, Deon", "Landry, Jarvis", "Larsen, Ted", "Lippett, Tony", "Lucas, Jordan", 
        "Maxwell, Byron", "McCain, Bobby", "Miley, Arthus", "Misi, Koa", "Moore, Matt", 
        "Okoye, Lawrence", "Pentale, Chris", "Parker, DeVante", "Perry, Senorise", "Phillips, Jordan",
        "Pitts, Lafayette", "Poole, Terry", "Pouncey, Mike", "Reiley, Trevor", "Scott, Rashawn",
        "Steen, Anthony", "Stills, Kenny", "Suh, Ndamukong", "Tannehill, Ryan", "Thomas, Julius",
        "Thomas, Michael", "Timmons, Lawrence", "Tunsil, Laremy", "Urbik, Kraig", "Wake, Cameron",
        "Warmsley, Julius", "Watts, Brandon", "Williams, Damien", "Williams, Nick", "Young, Avery",
        "Young, Sam", "Allen, Dwayne", "Allen, Ryan", "Amendola, Danny", "Andrews, David",
        "Barker, Chris", "Bates, Trevor", "Brady, Tom", "Brissett, Jacoby", "Brown, Malcom",
        "Burkhead, Rex", "Cannon, Marcus", "Cardona, Joe", "Chung, Patrick", "Coleman, Justin",
        "Cooks, Brandin", "Develin, James", "Douglas, Jamil", "Ealy, Kony", "Ebner, Nate",
        "Edelman, Julian", "Farris, Chase", "Flowers, Trey", "Foster, D.J.", "Freeny, Jonathan",
        "Garoppolo, Jimmy", "Gilmore, Stephon", "Gostkowski, Stephen", "Grissom, Geneo", 
        "Gronkowski, Glenn", "Gronkowski, Rob", "Guy, Lawrence", "Hamilton, Woodrow", "Harmon, Duron",
        "Hightower, Dont'a", "Hogan, Chris", "Housler, Rob", "Jackson, Tre", "Jones, Cyrus",
        "Jones, Jonathan", "Karras, Ted", "Kilgo, Darius", "Lewis, Dion", "Lucien, Devin",
        "Mason, Shaq", "McClellin, Shea", "McCourty, Devin", "Mitchell, Malcolm", "Ninkovich, Rob",
        "Richards, Jordan", "Roberts, Elandon", "Rowe, Eric", "Slater, Matthew", "Solder, Nate",
        "Thuney, Joe", "Valentine, Vincent", "Van Noy, Kyle", "Waddle, LaAdrian", "White, DeAndrew",
        "White, James", "Williams, Michael", "Adams, Jeff", "Anderson, Robby", "Anunike, Kenny", "Beachum, Kelvin",
        "Beltre, Frank", "Bishop, Freddie", "Bowman, Braedon", "Bryant, Brandin", "Burks, Brandon",
        "Burris, Juston", "Carpenter, James", "Catanzaro, Chandler", "Claiborne, Morris",
        "Decker, Eric", "Dozier, Dakota", "Edwards, Lachlan", "Enunwa, Quincy", "Forte, Matt",
        "Foxx, Deshon", "Gilchrist, Marcus", "Hackenberg, Christian", "Hammond, Frankie",
        "Harris, David", "Harrison, Jonnotthan", "Hawkins, Donald", "Howsare, Julian", 
        "Ijalana, Ben", "Jenkins, Jordan", "Jennings, Darius", "Johnson, Anthony", "Johnson, Randell",
        "Keeton, Bryson", "Latham, Josh", "Lee, Darron", "Lemonier, Corey", "Luc, Jeff",
        "Marshall, Jalin", "Marshall, Nick", "Martin, Josh", "Martin, Ronald", "Martin, Ross",
        "Mauldin, Lorenzo", "McCown, Josh", "McDougle, Dexter", "McLendon, Stever", "Middleton, Doug",
        "Miles, Rontez", "Morris, Romar", "Obioha, Julien", "Patton, Quinton", "Peake, Charone",
        "Pelon, Claude", "Pennel, Mike", "Petty, Bryce", "Powell, Bilal", "Pryor, Calvin", 
        "Purdum, Tanner", "Qvale, Brent", "Richardson, Sheldon", "Roberts, Darryl", 
        "Seferian-Jenkins, Austin", "Shell, Brandon", "Simon, Deon", "Skrine, Buster", "Smith, Devin",
        "Stanford, Julian", "Swain, Chris", "Thomas, Lawrence", "Tomlinson, Eric", "Triner, Zach",
        "Vander Laan, Jason", "Watts, Craig", "White, Myles", "Wilds, Brandon", "Wilkerson, Muhammad",
        "Williams, Leonard", "Winters, Brian", "Allen, Jeff", "Anderson, Stephen", "Ballentine, Lonnie", "Bergstrom, Tony",
        "Blue, Alfred", "Brown, Duane", "Bulloug, Max", "Clark, Chris", "Clowney, Jadeveon", 
        "Covington, Christian", "Cushig, Brian", "Dillion, K.J.", "Drummong, Kurtis", "Ervin, Tyler",
        "Fairbairn, Ka'imi", "Fiedorowicz, C.J.", "Fuller, Will", "Griffin, Ryan", "Hal, Andre", 
        "Heath, Joel", "Hopkins, DeAndre", "Hunt, Akeem", "Jackson, Kareem", "Johnson, Kevin", 
        "Joseph, Johnathan", "Kamalu, Ufomba", "Lamm, Kendall", "Lechler, Shane", "Mancz, Greg",
        "Martin, Nick", "McKinney, Benardrick", "Mercilus, Whitney", "Miller, Braxton", "Miller, Lamar",
        "Moore, Corey", "Mumphery, Keith", "Nelson, Robert", "Newton, Derek", "Novak, Nick", 
        "Peters, Brian", "Pleasant, Eddie", "Prosch, Jay", "Quessenberry, David", "Reader, D.J.",
        "Rice, Denzel", "Rivers, Gerald", "Savage, Tom", "Scarlett, Brennan", "Strong, Jaelan",
        "Su-a-Filo, Xavier", "Walker, Josh", "Washington, Tony", "Watt, J.J.", "Weeden, Brandon",
        "Weeks, Jon", "Williams, Wendall", "Aiken, Kamar", "Anderson, Henry", "Ayers, Akeem", "Bazzie, Alex",
        "Bell, Devon", "Blythe, Austin", "Bray, Quan", "Butler, Darius", "Cage, Isiah", 
        "Castonzo, Anthony", "Clark, Le'Raven", "Cooper, Fahn", "Davis, Vontae", "Dorsett, Phillip",
        "Doyle, Jack", "Edwards, Lavar", "Farley, Matthias", "Feguson, Josh", "Fortunato, Joe",
        "Geathers, Clayton", "Good, Denzelle", "Gore, Frank", "Green, T.J.", "Haeg, Joe", 
        "Hightower, Lee", "Hilton, T.Y.", "Hunt, Margus", "Jackson, Edwin", "James II, Charles",
        "Kelly, Ryan", "King, Deon", "Langford, Kendall", "Leak, Marcus", "Locke, Jeff", "Luck, Andrew",
        "Maggitt, Curt", "McClure, Stefan", "McGill, T.Y.", "Melvin, Rashaan", "Mewhort, Jack", 
        "Milton, Christopher", "Mingo, Barkevious", "Mitchel, Tevin", "Moncrief, Donte", 
        "Morris, Stephen", "Mount, Deiontrez", "Overton, Matt", "Parry, David", "Redmond, Adam",
        "Rhodes, Luke", "Ridgeway, Hassan", "Rogers, Chester", "Schwenke, Brian", "Scott, Larry",
        "Sheard, Jabaal", "Simon, John", "Smith, Tevaun", "Sokoli, Kristjan", "Spence, Sean", 
        "Strret, Devin", "Swoope, Erik", "Tolzien, Scott", "Turbin, Robert", "Vinatieri, Adam",
        "Vujnovich, Jeremy", "Williams, Brandon", "Williams, Duke", "Williams, Frankie", 
        "Williamson, Andrew", "Woods, Al", "Albert, Branden", "Allen, Brandon", "Benn, Arrelious",
        "Bennett, Michael", "Bibbs, E.J.", "Bortles, Bake", "Bouye, A.J.", "Bowanko, Luke",
        "Campbell, Calais", "Cann, A.J.", "Church, Barry", "Colvin, Aaron", "Davis, Akeem", "Day, Sheldon",
        "Ellis, Alex", "Fowler, Dante", "Gipson, Tashaun", "Grant, Corey", "Grant, Doran", 
        "Greene, Rashad", "Henne, Chad", "Hill, Bronson", "Hurns, Allen", "Ivory, Chris", "Jack, Myles",
        "Jackson, Malik", "Johnson, Josh", "Jones, Abry", "Kasitati, Nila", "Kelly, Colin", 
        "Kirby, Raphael", "Koyack, Ben", "Lee, Marqise", "Lewis, Marcedes", "Linder, Brandon",
        "McCray, Lerentee", "Myers, Jason", "Ngakoue, Yannick", "Nix, Louis", "Northman, Brad",
        "Omameg, Patrick", "Parnell, Jermey", "Porter, Sean", "Posluszny, Pauly", "Poutasi, Jeremiah",
        "Pullard, Hayes", "Ramsey, Jalen", "Reed, Chris", "Rivera, Mychal", "Robinson, Allen",
        "Robinson, Jamal", "Rush, Marcus", "Sample, James", "Shatley, Tyler", "Shumate, Eljah",
        "Sinclair, Gannon", "Skuta, Dan", "Smith, Chris", "Smith, Telvin", "Sterling, Neal",
        "Thompson, Peyton", "Tinker, Carson", "Uzdavinis, Arturo", "Van Roten, Greg", "Walters, Bryan",
        "Washington, Tony", "Wells, Josh", "Wilson, Jarrod", "Woodard, Jonathan", "Wynn, Shane",
        "Yeldon, T.J.", "Abdesmad, Mehdi", "Amaro, Jace", "Andrews, Antonio", "Barton, Karim",
        "Bass, David", "Bates, Daren", "Bell, Byron", "Blackson, Angelo", "Brinkley, Beau", 
        "Brown, Kourtnei", "Byard, Kevin", "Casey, Jurrell", "Cassel, Matt", "Cliett, Reshard",
        "Conklin, Jack", "Cunningham, Jerome", "Cyprien, Johnathan", "Dodd, Kevin", "Douglas, Harry",
        "Fluellen, David", "Fowler, Jalston", "Henry, Derrick", "Johnson, Austin", "Johnson, Rashad",
        "Jones, Ben", "Jones, DaQuan", "Kelly, Dennis", "Kern, Brett", "Kline, Josh", "Klug, Karl",
        "Krause, Jonathan", "Lelito, Tim", "Lewan, Taylor", "Lyons, Caushaud", "Mariani, Marc",
        "Mariota, Marcus", "Marz, Tyler", "Matias, Josue", "Matthews, Rishard", "Maye, K.J.",
        "McBride, Tre", "McCain, Brice", "McCourty, Jason", "Morgan, Derrick", "Murray, DeMarco",
        "Okotcha, Bennett", "Orakpo, Brian", "Palmer, Nate", "Reed, Kalan", "Riley, Curtis",
        "Ryan, Logan", "Searcy, Da'Norris", "Semisch, Tim", "Sharpe, Tajae", "Sims, LeShaun",
        "Smith, D'Joun", "Smith, Type", "Spain, Quinton", "Stafford, Daimion", "Staples, Justin",
        "Succop, Ryan", "Supernaw, Phillip", "Tanney, Alex", "Trawick, Brynden", "Tretola, Sebastian",
        "Walker, Delanie", "Wallace, Aaron", "Weems, Eric", "Williamson, Avery", "Williams, Sylvester",
        "Woods, Antwaun", "Woodyard, Wesley", "Anderson, C.J.", "Anderson, Zaire", "Barrett, Shaquil", "Biibs, Kapri",
        "Booker, Devontae", "Brooks, Zac", "Brown, Marlon", "Crick, Jared", "Davis, Todd",
        "Day, Dillon", "Derby, A.J.", "Dismukes, Reese", "Dixon, Riley", "Dora, Vontarrius",
        "Doss, Lorenzo", "Edebali, Kasim", "Ferentz, James", "Fowler III, Bennie", "Garcia, Max",
        "Gause, Quentin", "Gotsis, Adam", "Grren, Virgil", "Harris, Chris", "Heuerman, Jeff",
        "Iosia, Iosia", "Janovich, Andy", "Kerr, Zach", "Kreiter, Casey", "Krieger-Coble, Henry",
        "Latimer, Cody", "Leary, Ron", "Lynch, Paxton", "Marshall, Brandon", "McGovern, Connor",
        "McKay, Mekale", "McManus, Brandon", "Miller, Von", "Murray, Justin", "Nelson, Corey",
        "Nixon, Taurean", "Overbaugh, Jeff", "Paradis, Matt", "Parks, Will", "Peko, Domata", 
        "Peko, Kyle", "Pierce, Bernard", "Raciti, Travis", "Raymond, Kalif", "Ray, Shane", 
        "Richardson, Bobby", "Roby, Bradley", "Sambrailo, Ty", "Sanders, Emmanuel", "Scheu, Steven",
        "Schofield, Michael", "Sharp, Hunter", "Siemian, Trevor", "Simmons, Justin", "Synder, Kevin",
        "Stephenson, Donald", "Stewart, Darian", "Talib, Aqib", "Taylor, Jordan", "Turner, Billy",
        "Ward, T.J.", "Watson, Menelik", "Wolfe, Derek", "Acker, Kenneth", "Alexander, D.J.", "Bailey, Allen", "Barnes, T.J.",
        "Battle, Isaiah", "Berry, Eric", "Bray, Tyler", "Cheek, Joseph", "Colquitt, Dustin",
        "Conley, Chris", "Cook, Kenny", "Devey, Jordan", "Duvernay-Tardif, Laurent", "Ehinger, Parker",
        "Fisher, Eric", "Ford, Dee", "Fulton, Zach", "Gaines, Phillip", "Greene, Khaseem", "Hali, Tamba",
        "Hall, Jimmy", "Harris, Demetrius", "Harris, Vernon", "Hill, Tyreek", "Houston, Justin",
        "Howard, Jaye", "Huff, Marqueston", "Hughes, Montori", "James, Josh", "Johnson, Cory", 
        "Johnson, Derrick", "Jones, Chris", "Jones, Seantavius", "Kelce, Travis", "King, David", 
        "Logan, Bennie", "Maclin, Jeremy", "March-Lillard, Justin", "Millard, Trey", "Mitchell, Terrance",
        "Morse, Mitch", "Murray, Eric", "Nelson, Steven", "Nicolas, Dadi", "Nunez-Roches, Rakeem",
        "O'Shaughnessy, James", "Ochi, Victor", "Okine, Earl", "Parker, Ron", "Person, Mike", "Peters, Marcus",
        "Ratelle, Will", "Reaves, Darrin", "Reid, Jah", "Robinson, Demarcus", "Santos, Cairo", 
        "Scwartz, Mitchell", "Sherman, Anthony", "Smith, Alex", "Smith, Terrance", "Sorensen, Daniel",
        "Spiller, C.J.", "Stave, Joel", "Thomas, De'Anthony", "Travis, Ross", "Ware, Spencer", 
        "West, Charcandrick", "White, D.J.", "Wilson, Albert", "Wilson, Julian", "Wilson, Ramik", 
        "Winchester, James", "Witzmann, Bryan", "Zombo, Frank", "Addae, Jahleel", "Allen, Keenan", "Attaochu, Jerry",
        "Barksdale, Joe", "Barner, Kenjon", "Benjamin, Travis", "Bercovici, Mike", "Bosa, Joey", 
        "Bokyo, Brett", "Brown, Da'Ron", "Brown, Jatavis", "Burse, Isaiah", "Burwell, Tyreek",
        "Carlis, Zamir", "Carrethers, Ryan", "Clark, Donavon", "Clemens, Kellen", "Cleveland, Asante",
        "Cumberland, Jeff", "Davis, Geremy", "Dzubnar, Nick", "Emanuel, Kyle", "Eulls, Kaleb",
        "Evans, Randall", "Farrow, Kenneth", "Fields, Carlos", "Franklin, Orlando", "Gates, Antonio",
        "Gordon, Melvin", "Hairston, Chris", "Hayward, Casey", "Henry, Hunter", "Herndon, Javontee",
        "Hillman, Ronnie", "Ingram, Melvin", "Inman, Dontrelle", "Johnstone, Tyler", "Jones, Jamaal",
        "Kaser, Drew", "Lambo, Josh", "Landrum, Chris", "Lee, Mike", "Lissemore, Sean", "Liuget, Corey",
        "Lowery, Dwight", "Mager, Craig", "McCain, Chris", "McClain, Robert", "McCluster, Dexter",
        "McCoil, Dexter", "McDonald, Adrian", "McGee, Jake", "McGrath, Sean", "Mebane, Brandon",
        "Okung, Russell", "Oliver, Branden", "Palepoi, Tenny", "Perry, Joshua", "Perryman, Denzel",
        "Phillips, Adrian", "Philon, Darius", "Pulley, Spencer", "Reed, Trovon", "Reid, Caraun",
        "Rivers, Phillip", "Slauson, Matt", "Square, Damion", "Stuckey, Darrell", "Toomer, Korey",
        "Tuerk, Max", "Verett, Jason", "Watt, Derek", "Wiggins, Kenny", "Williams, Andre", 
        "Williams, Tourek", "Williams, Trevor", "Williams, Tyrell", "Windt, Mike", "Adams, Tyrell", "Alexander, Vadal", "Amerson, David", "Ball, Neiron",
        "Bean, Jimmy", "Brent, K.J.", "Calhoun, Shillique", "Carr, Derek", "Carrie, TJ", 
        "Cherry, Demetrius", "Condo, Jon", "Cook, Connor", "Cook, Jared", "Cooper, Amari", 
        "Cowser, James", "Crabtree, Michael", "Durden, Kenneth", "Edwards, Mario", "Ellis, Justin",
        "Feliciano, Jon", "Hamilton, Antonio", "Heeney, Ben", "Helfet, Cooper", "Holton, Johnny",
        "Howard, Austin", "Hudson, Rodney", "Irvin, Bruce", "Jackson, Branden", "Jackson, Gabe",
        "James, Cory", "Janikowski, Sebastian", "Jenkins, Jelani", "Jones, Taiwan", "Joseph, Karl",
        "King, Marquette", "Latham, Darius", "Mack, Khalil", "Manuel, EJ", "McDonald, Dexter",
        "McGill II, Keith", "Micken, Jaydon", "Mulumba, Andy", "Nelson, Reggie", "Newhouse, Marshall",
        "Norman, Dwayne", "O'Malley, Ryan", "Olawale, Jamize", "Omoile, Oni", "Osemele, Kelechi",
        "Patterson, Cordarrelle", "Penn, Donald", "Richard, Jalen", "Silberman, Ian", "Smith, Lee",
        "Smith, Sean", "Walford, Clive", "Ward, Jihad", "Washington, DeAndre", "Williams, Dan", "Addison, Bralon", "Amos, Adrian", "Amukamara, Prince", "Anderson, Dres",
        "Anderson, Jonathan", "Banks, Jonathan", "Barth, Connor", "Bausby, De'Vante", "Bellamy, Joshua",
        "Braunecker, Ben", "Braverman, Daniel", "Brown, Daniel", "Bullard, Jonathan", "Bush, Deon",
        "Callahan, Bryce", "Carey, Ka'Deem", "Cobb, David", "Compton, Tom", "Cooper, Marcus", 
        "Cunningham, Benny", "Demps, Quintin", "Edison, Cornelius", "Ferguson, Ego", "Floys, Leonard",
        "Freeman, Jerrell", "Fuller, Kyle", "Glenn, Jacoby", "Glennon, Mike", "Goldman, Eddie",
        "Grasu, Hroniss", "Hall, Deiondre", "Hicks, Akiem", "Houston-Carson, DeAndre", "Houston, Lamarr",
        "Howard, Jordan", "Jenkins, John", "Jones-Quartey, Harold", "Jones, Christian", "Kush, Eric",
        "Kwiatkoski, Nick", "Langford, Jeremy", "Lasike, Paul", "LeBlanc, Cre'Von", "Leno, Charles",
        "Lewis-Moore, Kapron", "Long, Kyle", "Massie, Bobby", "McManis, Sherrick", "McPhee, Pernell",
        "Meredith, Cameron", "Miller, Zach", "O'Donnell, Pat", "Perillo, Jutin", "Poehis, William",
        "Porter, Tracy", "Prosinski, Chris", "Pruitt, MyCole", "Randie, Reuben", "Reynolds, Rashaad",
        "Richardson, Cyrill", "Robertson-Harris, Roy", "Royal, Eddie", "Sanchez, Mark", "Scales, Patrick",
        "Shaw, Connor", "Sims, Dion", "Sitton, Josh", "Sutton, Will", "Thompson, Deonte", "Timu, John",
        "Trevathan, Danny", "Unrein, Mitch", "Wheaton, Markus", "Whitehair, Cody", "White, Kevin",
        "Wilson, C.J.", "Wright, Kendall", "Young, Willie", "Abbrederis, Jared", "Abdullah, Ameer", "Ansah, Ezekiel", "Armbrister, Thurston",
        "Backman, Kennard", "Bademosi, Johnson", "Barnes, Adairius", "Billinsley, Jace", "Bryant, Armonty",
        "Burton, Michael", "Burton, Pierce", "Carey, Don", "Carter, Alex", "Chubb, Brandon", "Copeland, Brandon",
        "Dahl, Joe", "Decker, Taylor", "Diggs, Quandre", "Ebron, Eric", "Fells, Darren", 
        "Glasgow, Graham", "Hayden, DJ", "Hill, Jordan", "Hyder, Kerry", "James, Mike", "Jones, Marvin",
        "Jones, TJ", "Killebre, Miles", "Landes, Jimmy", "Lang, T.J.", "Lawson, Nevin", "Lee, Khari",
        "Longa, Steve", "Martin, Keshawn", "Martin, Sam", "Milligan, Rolan", "Muhlbach, Don", "Ngata, Haloti",
        "Prater, Matt", "Quin, Glover", "Riddick, Theo", "Robinson, A'Shawn", "Robinson, Corey", 
        "Rotteram, Matt", "Rudock, Jake", "Slay, Darius", "Spadola, Ryan", "Spence, Akeem", "Stafford, Matthew",
        "Swanson, Travis", "Tate, Golden", "Thomas, Brandon", "Thornton, Khyri", "Tomlinson, Laken", "Turzilli, Andrew",
        "Wagner, Rick", "Washington, Charles", "Washington, Cornelius", "Washington, Dwayne", "Wells, Ian",
        "Whitehead, Tahir", "Wick, Cole", "Williams, Antwione", "Wilson, Tavon", "Worrilow, Paul", "Zenner, Zach",
        "Zettel, Anthony", "Adams, Davante", "Bakhtiari, David", "Barclay, Don", "Bennett, Martellus",
        "Brice, Kentrell", "Bulaga, Bryan", "Burnett, Morgan", "Callahan, Joe", "Clark, Kenny", 
        "Clinton-Dix, Ha Ha", "Cobb Randall", "Crosby, Mason", "Daniels, Mike", "Davis, Trevor",
        "Dorleant, Makinton", "Elliott, Jayrone", "Evans, Marwin", "Fackrell, Kyler", "Flores, Jacob",
        "Gilbert, Reggie", "Goodley, Antwan", "Goodson, Demetri", "Guion, Letroy", "Gunter, LaDarius",
        "Hawkins, Josh", "House, Davon", "Hundley, Brett", "Janis, Jeff", "Jean Francois, Ricky", 
        "Kendricks, Lance", "Kerridge, Joe", "Linsley, Corey", "Lowry, Dean", "Martinez, Black", 
        "Mathews, Derrick", "Matthews, Clay", "McCaffrey, Max", "McCray, Justin", "Michael, Christine",
        "Montgomery, Ty", "Murphy, Kyle", "Nelson, Jordy", "Patrick, Lucas", "Pepper, Taybor", "Perry, Nick",
        "Price, Brian", "Randall, Damarious", "Ropkowski, Aaron", "Rodgers, Richard", "Rollins, Quinten",
        "Ryan, Jake", "Sandland, Beau", "Schum, Jacob", "Spriggs, Jason", "Taylor, Lane", "Thomas, Joe",
        "Tripp, Jordan", "Watersm Herb", "Whitehead, Jermaine", "Alexander, Mackensie", "Bailey, Sterline", "Barr, Anthony", "Beavers, Willie",
        "Berger, Joe", "Boone, Alex", "Bradford, Sam", "Bridgewater, Teddy", "Brothers, Kentrell", "Bohringer, Moritz",
        "Carter, Kyle", "Clemmings, T.J.", "Diggs, Stefon", "Dubose, B.J.", "Easton, Nick", 
        "Exum, Antone", "Floyd, Sharrif", "Forbath, Kai", "Fragel, Reid", "Fruechte, Isaac", "Griffen, Everson",
        "Ham, C.J.", "Harris, Anthony", "Heinicke, Taylor", "Hill, Rashod", "Hunter, Danielle",
        "Johnson, Toby", "Johnson, Tom", "Jones, Cayleb", "Jones, Datone", "Joseph, Linval",
        "Kearse, Jayron", "Kendricks, Eric", "Koehn, Marshall", "Lamur, Emmanuel", "Lucas, Marquis",
        "Matthews, Mitch", "McDermott, Kevin", "McKinnon, Jerick", "Morgan, David", "Murray, Latavius",
        "Newman, Terence", "Price, Jabari", "Reiff, Riley", "Remmers, Mike", "Rhodes, Xavier", 
        "Roberson, Tre", "Robinson, Edmond", "Robinson, Brian", "Rudolph, Kyle", "Sankey, Bishop",
        "Sendejo, Andrew", "Shepherd, Austin", "Sherels, Marcus", "Sinkfield, Terrell", "Sirles, Jeremiah",
        "Smith, Harrison", "Stephen, Shamar", "Symmank, Taylor", "Thielen, Adam", "Thompson, Cedric",
        "Treadwell, Laquon", "Truesdell, Nick", "Waynes, Trae", "Weatherly, Stephen", "Wright, Jarius", "Alford, Robert", "Allen, Ricardo", "Beasley, Vic", "Bosher, Matt",
        "Bryant, Matt", "Bykowski, Carter", "Campbell, De'Vondre", "Clayborn, Adrian", "Coleman, Tevin",
        "Collins, Jalen", "Crawford, Jack", "Dable, Anthony", "Daniels, B.J.", "Freeman, Devonta",
        "Fuller, Devin", "Gabriel, Taylor", "Garland, Ben", "Goodwin, C.J.", "Graf, Kevin", "Griswold, Darion",
        "Hageman, Ra'Shede", "Hardy, Jutin", "Harris, Josh", "Hooper, Austin", "Ifedi, Martin", "Ishmael, Kemal",
        "Jarrett, Grady", "Jones, Deion", "Jones, Julio", "Keyes, Josh", "King, Akeem", "Levitre, Andy",
        "Mack, Alex", "Matthews, Jake", "Mayes, Chris", "Meyer, Mike", "Muir, Blake", "Neal, Keanu",
        "Neasman, Sharrod", "Olatoye, Deji", "Perkins, Joshua", "Poe, Dontari", "Poole, Brian",
        "Reed, Brooks", "Reynolds, LaRoy", "Roberts, Andre", "Robinson, Trevor", "Ryan, Matt", "Sanu, Mohamed",
        "Schaub, Matt", "Schraeder, Ryan", "Schweitzer, Wes", "Shelby, Derrick", "Staten, Jimmy", "Tialavea, D.J.",
        "Toilolo, Levine", "Trufant, Desmond", "Upshaw, Courtney", "Vellano, Joe", "Vogler, Brian",
        "Ward, Terron", "Williams, Nick", "Wreh-Wilson, Blidi", "Adams, Mike", "Addison, Mario", "Anderson, Derek", "Artis-Payne, Cameron",
        "Benjamin, Kelvin", "Bersin, Brenton", "Blechen, Brian", "Boston, Tre", "Bradberry, James", 
        "Butler, Vernon", "Byrd, Damiere", "Cash, Jeremy", "Clausell, Blaine", "Coleman, Kurt", 
        "Crume, Eric", "Davis, Thomas", "Delaire, Ryan", "Dickson, Ed", "Dixon, Travell", "France, Dan",
        "Frazier, Mose", "Funchess, Devin", "Gano, Graham", "Garrett, Kayarris", "Gilbert, Garrett",
        "Gradkowski, Gino", "Horton, Wes", "Jacobs, Ben", "Jansen, J.J.", "Johnson, Charles", "Johnson, Charles",
        "Jones, Colin", "Kalil, Matt", "Kuechly, Luke", "Larsen, Tyler", "Lee, Andy", "Lotulelei, Star", 
        "Love, Kyle", "Manhertz, Chris", "Marlowe, Dean", "Mayo, David", "McCray, L.J.", "Munnerlyn, Captain",
        "Newton, Cam", "Norris, Jared", "Norwell, Andrew", "Oher, Michael", "Olsen, Greg", "Palardy, Michael",
        "Patmon, Tyler", "Peppers, Julius", "Richards, Jeff", "Rigsbee, Jordan", "Rodgers, Jake", "Sanchez, Zack",
        "Scott, Chris", "Shepard, Russel", "Short, Kawann", "Silatolu, Amini", "Simmons, Jalen", 
        "Simmonson, Scott", "Slater, Pearce", "Southward, Dezmen", "Stewart, Jonathan", "Thompson, Shaq",
        "Thompson, Tyrus", "Turner, Trai", "Wallace, Eric", "Webb, Joe", "Webster, Larry", "Whittaker, Fozzy",
        "Williams, Daryl", "Williams, Teddy", "Worley, Daryl", "Yankey, David", "Young, Darrel", "Young, Lou", "Allen, Jack", "Anthony, Stephone", "Armstead, Terron", "Banjo, Chris",
        "Bell, Vonn", "Bighill, Adam", "Breaux, Delvin", "Brees, Drew", "Calhoun, Taveze", "Coleman, Brandon",
        "Crawley, Ken", "Davison, Tyeler", "Ellerbe, Dannell", "Fairley, Nick", "Feeney, Travis", "Fleener, Coby",
        "Fuller, Corey", "Fullington, John", "Gaitor, Anthony", "Ginn, Tedd", "Grayson, Garrett", "Griffin, Garrett",
        "Gwacham, Obum", "Harris, De'Vante", "Harris, Erik", "Hightower, Forrest", "Hill, Josh",
        "Hoomanawanul, Michael", "Ingram, Mark", "Jordan, Cameron", "Kelemete, Senio", "Keo, Shiloh",
        "Kikaha, Hau'oli", "Klein, A.J.", "Kuhn, John", "LaFrance, Royce", "Lampman, Jake", "Lasco, Daniel",
        "Lawrence, Rashad", "Lewis, Tommylee", "Loewen, Mitchell", "Lutz, Wili", "Marby, Ashaad", 
        "McCown, Luke", "Moore, Sterling", "Morstead, Thomas", "Murphy, Marcus", "Okafor, Alex", 
        "Onyemata, David", "Peat, Andrus", "Pettway, D.J.", "Phillips, John", "Pruitt, Jimmy",
        "Rankins, Sheldon", "Robertson, Criag", "Snead IV, Willie", "Stoneburner, Jake", "Strief, Zach",
        "Stupar, Nathan", "Swann, Damian", "Tapp, Darryl", "Te'o Manti", "Therezie, Robenson", "Thomas, Michael",
        "Turner, Landon", "Unger, Max", "Vaccaro, Kenny", "Warford, Larry", "Williams-Lambert, Jordan",
        "Williams, P.J.", "Young, Avery", "Zimmer, Justin", "Aguayo, Roberto", "Alexander, Kwon", "Allen, Josh", "Anger, Bryan",
        "Ayers, Robert", "Baker, Chris", "Barber, Peyton", "Benenoch, Caleb", "Bond, Devante", 
        "Cartwright, Kivon", "Conte, Chris", "Cross, Alan", "David, Lavonte", "Dellenbach, Dax",
        "Doton, Demar", "Dye, Donteea", "Elliott, Javien", "Evans, Mike", "Folk, Nick",
        "Gholston, William", "Gottschalk, Ben", "Grimes, Brent", "Hanbrough, Russell", "Hargreaves, Vernon",
        "Harrison, Jarvis", "Hawley, Joe", "Hicks, Quayvon", "Huff, Josh", "Jackson, DaSean", "Johnson, Austin",
        "Johnson, George", "Johnson, Isaiah", "Knox, Jeff", "Lambert, DaVonte", "Liedtke, Michael",
        "Lynch, Cameron", "Marpet, Ali", "Martin, Doug", "McCoy, Gerald", "McDonald, Clinton",
        "Pamhile, Kevin", "Reedy, Bernard", "Renfree, Sean", "Riggs, Cody", "Robinson, Josh",
        "Rodgers, Jacquizz", "Russell, Ryan", "Sanborn, Garrison", "Silga, Sealver", "Sims, Black",
        "Sims, Charles", "Smith, Donovan", "Smith, Evan", "Smith, Ryan", "Spence, Noah", "Stocker, Luke",
        "Stone, James", "Sweezy, J.R.", "Tandy, Keith", "Walker, Derel", "Ward, Channing", 
        "Westbrook, Tevin", "Wester, Leonard", "Wilcox, J.J", "Winston, Jameis", "Ash, Richard", "Bailey, Dan", "Beasley, Cole", "Bell, Byron", "Brown, Anthony",
        "Bryant, Dez", "Butler, Brice", "Carroll, Nolan", "Cleary, Emmett", "Collins, Maliek", "Crawford, Tyrone",
        "Durant, Justin", "Elliott, Ezekiel", "Frazier, Kavon", "Frederick, Travis", "Free, Doug",
        "Gregory, Randy", "Heath, Jeff", "Hitchens, Anthony", "Irving, David", "Jones, Byron",
        "Jones, Chris", "LaDouceur, L.P.", "Lawrence, Demarcus", "Lee, Sean", "Looney, Joe",
        "Martin, Zack", "Mayowa, Benson", "McClain, Terrell", "McFadden, Leon", "Moore, Damontre",
        "Morris, Alfred", "Nzeocha, Mark", "Paea, Stephen", "Prescott, Dak", "Romo, Tony", 
        "Scandrick, Orlando", "Smith, Keith", "Smith, Tyron", "Thornton, Cedric", "Whitehead, Lucky",
        "Wilber, Kyle", "Williams Terrance", "Wilson, Damien", "Witten, Jason", "Adams, Andrew", "Adams, Jerell", "Apple, Eli", "Beckham, Odell",
        "Berhe, Nat", "Blake, Valentino", "Bowie, Michael", "Bromley, Jay", "Casillas, Jonathan",
        "Collins, Landon", "Darkwa, Orleans", "Deayon, Donte", "DeOssie, Zak", "Draughn, Shaun",
        "Ellison, Rhett", "Flowers, Ereck", "Fluker, D.J.", "Gettis, Adam", "Goodson, B.J.",
        "Grant, Curtis", "Halapio, Jon", "Harris, Dwayne", "Harrison, Damon", "Hart, Bobby",
        "Herzlich, Mark", "Holmes, Khaled", "Huesman, Jacob", "Hunter, Michael", "Jenkins, Janoris",
        "Jerry, John", "Johnson, Josh", "Jones, Brett", "Kennard, Devon", "King, Tavarres",
        "LaCosse, Matt", "Lewis, Roger", "Manning, Eli", "Maponga, Stansly", "Marshall, Brandon",
        "Moore, Rahim", "Murphy, Ryan", "Norwood, Kevin", "Odighizuwa, Owa", "Okwara, Romeo",
        "Perkins, Paul", "Pierre-Paul, Jason", "Pinkins, Eric", "Powe, Darius", "Pugh, Justin",
        "Richburg, Weston", "Robinson, Keenan", "Rodgers-Cromartie, Dominique", "Rosas, Aldrick",
        "Shepard, Sterline", "Skinner, Deontae", "Smith, Geno", "Thomas, J.T.", "Thomas, Robert",
        "Thompson, Darian", "Thompson, Mykkele", "Tye, Will", "Vereen, Shane", "Vernon, Olivier",
        "Virgies, Daryl", "Wallace, Martin", "Wenning, Keith", "Williams, Ishaq", "Williams, Jordan",
        "Wing, Brad", "Winn, George", "Wynn, Kerry", "Agholor, Nelson", "Allen, Beau", "Andrews, Josh", "Bailey, Rasheed",
        "Barbre, Allen", "Bonnet, Andrew", "Bradham, Nigel", "Brooks, Brandon", "Brooks, Ron",
        "Brooks, Terrence", "Celek, Brent", "Cherry, Don", "Cox, Fletcher", "Curry, Vinny",
        "Denham, Anthony", "Dorenbos, Jon", "Ertz, Zach", "Foles, Nick", "Goode, Najee", "Gordon, Dillon",
        "Graham, Brandon", "Gratz, Dwayne", "Green-Beckham, Dorial", "Greene, Darrell", "Grugier-Hill, Kamu",
        "Grymes, Aaron", "Hamilton, Justin", "Hart, Taylor", "Hicks, Jordan", "Jeffery, Alshon", 
        "Jenkins, Malcolm", "Johnson, Lane", "Johnson, Marcus", "Jones, Donnie", "Kelce, Jason", 
        "Kenricks, Mychal", "LeRibeus, Josh", "Long, Chris", "Lovato, Rick", "Maragos, Chris", "Marshall, Byron",
        "Matthews, Ryan", "Matthews, Jordan", "McCalister, Alex", "McLeod, Rodney", "Means, Steven",
        "Mills, Jalen", "Neary, Aaron", "Peters, Jason", "Robinson, Patrick", "Seumalo, Isaac", 
        "Shittu, Aziz", "Smallwood, Wendell", "Smith, C.J.", "Smith, Marcus", "Smith, Torrey",
        "Sproles, Darren", "Sturgis, Caleb", "Thomas, Dallas", "Tobin, Matt", "Treggs, Bryce",
        "Turner, Paul", "Vaeao, Destiny", "Vaitai, Halapoulivaati", "Walker, Joe", "Warmack, Chance",
        "Watford, David", "Watkins, Jaylen", "Watson, Terrell", "Wentz, Carson", "White, Mitchell",
        "Williams, Dom", "Wisniewski, Stefen", "Bates, Houston", "Blackmon, Will", "Bowen, Kevin", "Breeland, Bashaud",
        "Brown, Mack", "Carrier, Derek", "Carter, Chris", "Cousins, Kirk", "Cravens, Su'a", "Crowder, Jamison",
        "Daniels, Steven", "Davis, Vernon", "Diggs, Reggie", "Doctson, Josh", "Dunbar, Quinton",
        "Evans, Josh", "Everett, Deshazor", "Fortt, Khairi", "Foster, Mason", "Francis, A.J.", "Fuller, Kendall",
        "Galette, Junior", "Grand, Ryan", "Hall, DeAngelo", "Harris, Maurice", "Hazer, Matt", "Hood, Ziggy",
        "Hopkins, Dustin", "Ioannidis, Matt", "Johnson, Rufus", "Jones, Matt", "Kelley, Robert",
        "Kerrigan, Ryan", "Kouandjio, Arie", "Lanier, Anthony", "Lauvao, Shawn", "Long, Spencer",
        "Marshall, Keith", "Mbu, Joey", "McClain, Terrell", "McCoy, Colt", "McGee, Stacy", "Moses, Morgan",
        "Murphy, Trent", "Norman, Josh", "Nsekhe, Ty", "Painter, Vinston", "Patrick, Ronald", "Paul, Niles",
        "Pyor, Terrelle", "Quick, Brian", "Randolph, Shak", "Reed, Jordan", "Robertson, Pete", "Saxton, Wes",
        "Scherff, Brandon", "Simon, Tharold", "Smith, Preston", "Spaight, Martrell", "Sudfeld, Nate",
        "Sundberg, Nick", "Swearinger, D.J.", "Taylor, Phil", "Thompson, Kendal", "Trail, Lynden", "Vigil, Zach",
        "Way, Tress", "Williams, Isaiah", "Williams, Trent", "Wolff, Earl", "Bethea, Antoine", "Bethel, Justin", "Binford, Harvey", "Boehm, Evan",
        "Bouka, Elie", "Branch, Tyvon", "Brewer, Aaron", "Brown, Jaron", "Brown, John",
        "Bryant, Christian", "Bucannon, Deone", "Bundy, Marquis", "Capi, Cap", "Dansby, Karlos",
        "Dawson, Phil", "Dixon, Brian", "Dobson, Aaron", "Dysert, Zac", "Ellington, Andre",
        "Fitzgerald, Larry", "Fua, Alani", "Golden, Brittan", "Golden, Markus", "Gooden, Zaviar",
        "Gresham, Jermaine", "Gunter, Rodney", "Hall, Marvin", "Hartfield, Trevon", "Hubert, Chris",
        "Humphries, D.J.", "Iupati, Mike", "Johnson, David", "Johnson, Kaleb", "John, Ulrick",
        "Jones, Chandler", "Jones, Jarvis", "Leone, Richie", "Martin, Gabe", "Martin, Kareem",
        "Mathieu, Tyrann", "Mauro, Josh", "Miller, Harlan", "Momah, Ifeanyi", "Munyer, Daniel",
        "Nelson, J.J.", "Niklas, Troy", "Nkemdiche, Robert", "Palmer, Carson", "Penny, Elijhaa",
        "Peters, Corey", "Peterson, Patrick", "Pierre, Olsen", "Ross, Jeremy", "Rucker, Frostee",
        "Shipley, A.Q.", "Stanton, Drew", "Stinson, Ed", "Toner, Cole", "Valles, Hakeem",
        "Veldheer, Jared", "Wetzel, John", "Wile, Matt", "Williams, Brandon", "Williams, Kerwynn",
        "Williams, Xavier", "Wright, Scooby", "Zamort, Ronald", "Alexander, Maurice", "Arkin, David", "Austin, Tavon", "Barron, Mark",
        "Barwin, Connor", "Brockers, Michael", "Brown, Jamon", "Brown, Malcolm", "Christian, Marqui",
        "Cooper, Pharoh", "Countess, Blake", "Couplin, Jerome", "Davis, Cody", "Donald, Aaron", 
        "Donnal, Andrew", "Dunbar, Lance", "Easley, Dominique", "East, Andrew", "Forrest, Josh", 
        "Fox, Morgan", "Gaines, E.J.", "Goff, Jared", "Green, Aaron", "Grigsby, Nicholas", "Gurley, Todd",
        "Hager, Bryce", "Harkey, Cory", "Havenstein, Rob", "Hekker, Johnny", "Hemingway, Temarrick",
        "Higbee, Tyler", "Hill, Troy", "Johnson, Isaiah", "Johnson, Trumaine", "Jordan, Mike", 
        "Joyner, Lamarcus", "Laskey, Zach", "Litteton, Cory", "Longacre, Matt", "Mannion, Sean", 
        "Marquez, Bradley", "McKinzy, Cassanova", "McQuiade, Jake", "McRoberts, Paul", "Murphy, Pace",
        "Murray, Aaron", "North, Marquez", "Northrup, Reggie", "Ogletree, Alec", "Peterson, Kevin",
        "Quinn, Robert", "Randolph, Brian", "Rhaney, Demetrius", "Robinson, Greg", "Saffold, Rodger",
        "Shippen, Brandon", "Short, Kevin", "Spruce, Nelson", "Thomas, Mike", "Trinca-Pasat, Louis",
        "Walker, Tyrunn", "Webster, Kayvon", "Wegher, Brandon", "Westbrooks, Ethan", "Whitworth, Andrew",
        "Wichmann, Cody", "Williams, Bryce", "Williams, Darrell", "Wilson, Travis", "Woods, Robert",
        "Zuerlein, Greg", "Armstead, Arik", "Armstrong, Ray-Ray", "Balducci, Alex", "Ball, Marcus",
        "Barkley, Matt", "Beadles, Zane", "Bell, Blake", "Blair, Ronald", "Bowman, NaVorro", "Bradford, Carl",
        "Brock, Tramaine", "Brooks, Ahmad", "Brown, Trent", "Buckner, DeForrest", "Burbridge, Aaron",
        "Carradine, Tank", "Carter, DeAndre", "Celek, Garrett", "Coyle, Brock", "Davis, Mike", "Dial, Quinton",
        "Ellington, Bruce", "Garnett, Joshua", "Garcon, Pierre", "Goodwin, Marquise", "Gould, Marquise",
        "Hamm, Je'Ron", "Harold, Eli", "Harper, Chris", "Harris, DuJuan", "Hoyer, Brian", "Hyde, Carlos",
        "Iworah, Prince Charles", "Johnson, Dontae", "Jones, Chris", "Jones, Don", "Juszczyk, Kyle",
        "Kerley, Jeremy", "Kilgore, Daniel", "Lynch, Aaron", "McDonald, Vance", "McManis, Wynton", "Miller, Brock",
        "Mitchell, Earl", "Moore, Zach", "Mostert, Raheem", "Nelson, Kyle", "Paulsen, Logan",
        "Pinion, Bradley","Price, Norman", "Purcell, Mike", "Reaser, Keith", "Redmond, Will",
        "Reid, Eric", "Robinson, Aldrick", "Robinson, Rashard", "Rogers, Eric", "Rose, Nick",
        "Ross, Rashad", "Shepherd, JaCorey", "Skov, Shayne", "Smeter, DeAndre", "Smith, Malcolm",
        "Stanley, Joe", "Sunseri, Vinnie", "Tartt, Jaquiski", "Theus, John", "Ward, Jimmie",
        "Watson, Dekoda", "Williams, K'Waun", "Zuttah, Jeremy", "AAboushi, Oday", "Avril, Cliff", "Baldwin, Doug", "Bennett, Michael",
        "Boykin, Trevone", "Briggs, Chris", "Britt, Justin", "Brown, Arthur", "Burbank, Ross", 
        "Chancellor, Kam", "Clark, Frank", "Coe, Rodney", "Collins, Alex", "Cox, Perrish", 
        "Desir, Pierre", "Elliott, DeAndre", "Fant, George", "Farmer, George", "Frese, Nolan",
        "Garvin, Terence", "Gilliam, Garry", "Glowinski, Mark", "Graham, Jimmy", "Harris, Tylor",
        "Hunt, Joey", "Ifedi, Germain", "Jefferson, Quinton", "Jenkins, Shanell", "Joeckel, Luke",
        "Johnson, Jamel", "Johnson, Malcolm", "Kearse, Jermaine", "Lacy, Eddie", "Lane, Jeremy",
        "Lawler, Kenny", "Lockett, Tyler", "Lucas, Marcus", "Lunsord, Tyler", "Madden, Tre",
        "Magee, Terrence", "Marsh, Cassus", "McCray, Demetrius", "McDonald, Dewey", "McDougald, Bradley",
        "McEvoy, Tanner", "McKissic, J.D.", "Myers, Robert", "Odhiambo, Rees", "Ott, Tyler", "Periack, Will",
        "Pierre-Louis, Kevin", "Pope, Troymaine", "Powell, Ronald", "Prosise, C.J.", "Rawis, Thomas",
        "Reed, Jarran", "Richardson, Paul", "Rubin, Ahtyba", "Ryan, Jon", "Shead, DeShawn", "Sherman, Richard",
        "Smith, Garrison", "Smith, Rodney", "Taylor, Kelvin", "Thomas, Earl", "Thorpe, Neiko", "Vannett, Nick",
        "Wagner, Bobby", "Walsh, Blair", "Wilhoite, Michael", "Williams, Kasen", "Willson, Luke",
        "Wilson, Russell", "Wright, K.J."};

}
